# Generated by Django 6.1 on 2026-09-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
