# Generated by Django 6.1 on 2026-09-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApp', '0007_product_material_product_reference_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
